# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/person.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/person.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12proto/person.proto\x12\x05proto\"&\n\x06PERSON\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08username\x18\x02 \x01(\t\",\n\x0cPERSON_ARRAY\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.proto.PERSONb\x06proto3')
)




_PERSON = _descriptor.Descriptor(
  name='PERSON',
  full_name='proto.PERSON',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.PERSON.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='proto.PERSON.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=67,
)


_PERSON_ARRAY = _descriptor.Descriptor(
  name='PERSON_ARRAY',
  full_name='proto.PERSON_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='proto.PERSON_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=113,
)

_PERSON_ARRAY.fields_by_name['items'].message_type = _PERSON
DESCRIPTOR.message_types_by_name['PERSON'] = _PERSON
DESCRIPTOR.message_types_by_name['PERSON_ARRAY'] = _PERSON_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PERSON = _reflection.GeneratedProtocolMessageType('PERSON', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'proto.person_pb2'
  # @@protoc_insertion_point(class_scope:proto.PERSON)
  ))
_sym_db.RegisterMessage(PERSON)

PERSON_ARRAY = _reflection.GeneratedProtocolMessageType('PERSON_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _PERSON_ARRAY,
  __module__ = 'proto.person_pb2'
  # @@protoc_insertion_point(class_scope:proto.PERSON_ARRAY)
  ))
_sym_db.RegisterMessage(PERSON_ARRAY)


# @@protoc_insertion_point(module_scope)
