# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/WordConfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/WordConfig.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16proto/WordConfig.proto\x12\x05proto\"\'\n\nWordConfig\x12\n\n\x02ID\x18\x01 \x01(\r\x12\r\n\x05Words\x18\x02 \x01(\t\"\x80\x01\n\rWordConfigMap\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.proto.WordConfigMap.ItemsEntry\x1a?\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.proto.WordConfig:\x02\x38\x01\x62\x06proto3')
)




_WORDCONFIG = _descriptor.Descriptor(
  name='WordConfig',
  full_name='proto.WordConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='proto.WordConfig.ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Words', full_name='proto.WordConfig.Words', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=72,
)


_WORDCONFIGMAP_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='proto.WordConfigMap.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.WordConfigMap.ItemsEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.WordConfigMap.ItemsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=203,
)

_WORDCONFIGMAP = _descriptor.Descriptor(
  name='WordConfigMap',
  full_name='proto.WordConfigMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='proto.WordConfigMap.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_WORDCONFIGMAP_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=203,
)

_WORDCONFIGMAP_ITEMSENTRY.fields_by_name['value'].message_type = _WORDCONFIG
_WORDCONFIGMAP_ITEMSENTRY.containing_type = _WORDCONFIGMAP
_WORDCONFIGMAP.fields_by_name['items'].message_type = _WORDCONFIGMAP_ITEMSENTRY
DESCRIPTOR.message_types_by_name['WordConfig'] = _WORDCONFIG
DESCRIPTOR.message_types_by_name['WordConfigMap'] = _WORDCONFIGMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WordConfig = _reflection.GeneratedProtocolMessageType('WordConfig', (_message.Message,), dict(
  DESCRIPTOR = _WORDCONFIG,
  __module__ = 'proto.WordConfig_pb2'
  # @@protoc_insertion_point(class_scope:proto.WordConfig)
  ))
_sym_db.RegisterMessage(WordConfig)

WordConfigMap = _reflection.GeneratedProtocolMessageType('WordConfigMap', (_message.Message,), dict(

  ItemsEntry = _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), dict(
    DESCRIPTOR = _WORDCONFIGMAP_ITEMSENTRY,
    __module__ = 'proto.WordConfig_pb2'
    # @@protoc_insertion_point(class_scope:proto.WordConfigMap.ItemsEntry)
    ))
  ,
  DESCRIPTOR = _WORDCONFIGMAP,
  __module__ = 'proto.WordConfig_pb2'
  # @@protoc_insertion_point(class_scope:proto.WordConfigMap)
  ))
_sym_db.RegisterMessage(WordConfigMap)
_sym_db.RegisterMessage(WordConfigMap.ItemsEntry)


_WORDCONFIGMAP_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
